######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 25 12:34:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /tmp/hooktest/hooked/. .

# Input
SOURCES += main.cpp
