######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 25 12:40:00 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += GlobalEventHook.h
SOURCES += GlobalEventHook.cpp main.cpp
