######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 25 12:40:00 2009
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /tmp/hooktest/hook/. .
CONFIG += debug

# Input
SOURCES += main.cpp
