######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 26 12:24:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/fred/git/hooktest/hooklib/. .

# Input
HEADERS += GdbInjector.h Injector.h
SOURCES += GdbInjector.cpp Injector.cpp main.cpp
