Document: hooq
Title: Debian hooq Manual
Author: <insert document author here>
Abstract: This manual describes what hooq is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hooq/hooq.sgml.gz

Format: postscript
Files: /usr/share/doc/hooq/hooq.ps.gz

Format: text
Files: /usr/share/doc/hooq/hooq.text.gz

Format: HTML
Index: /usr/share/doc/hooq/html/index.html
Files: /usr/share/doc/hooq/html/*.html


